# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение отзыва', null=True, upload_to='', verbose_name='Изображение')),
                ('min_image', models.ImageField(blank=True, help_text='Выберите миниатюру отзыва', null=True, upload_to='', verbose_name='Миниатюра')),
                ('name', models.CharField(default='Отзыв', max_length=250, verbose_name='Название отзыва')),
                ('brief', models.CharField(blank=True, help_text='Не более 500 знаков', max_length=500, null=True, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='min_image',
            field=models.ImageField(blank=True, help_text='Выберите миниатюру новости', null=True, upload_to='', verbose_name='Миниатюра'),
        ),
    ]
