# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171004_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
    ]
