# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spoiler1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Spoiler 1',
            },
        ),
        migrations.CreateModel(
            name='Spoiler2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Spoiler 2',
            },
        ),
        migrations.CreateModel(
            name='Spoiler3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Spoiler 3',
            },
        ),
        migrations.CreateModel(
            name='SpoilerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Spoiler for page',
            },
        ),
        migrations.CreateModel(
            name='SpoilerPageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Spoiler for page with banner',
            },
        ),
    ]
