# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler', '0002_auto_20171002_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiler1',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='spoiler2',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='spoiler3',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='spoilerpage',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='spoilerpagebanner',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
    ]
