# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler', '0007_auto_20171002_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiler1',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spoiler2',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spoiler3',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spoilerpage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spoilerpagebanner',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
