# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler', '0009_delete_spoilerpagebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiler1',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='spoiler2',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='spoiler3',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='spoilerpage',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
    ]
