# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(help_text='Выберите изображение', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
