# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170926_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
