# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170926_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 9, 27), null=True, verbose_name='Дата'),
        ),
    ]
