# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170927_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, help_text='Введите адрес контактов', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, help_text='Введите email контактов', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Введите часы работы в виде: Monday - Friday: 9:00 AM to 5:00 PM', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон контактов', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_four',
            field=models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети компании', max_length=500, null=True, verbose_name='URL-адрес 4'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_one',
            field=models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети компании', max_length=500, null=True, verbose_name='URL-адрес 1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_three',
            field=models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети компании', max_length=500, null=True, verbose_name='URL-адрес 3'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_two',
            field=models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети компании', max_length=500, null=True, verbose_name='URL-адрес 2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 9, 29), null=True, verbose_name='Дата'),
        ),
    ]
