# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171002_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
