# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171002_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
