# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 3), null=True, verbose_name='Дата'),
        ),
    ]
