# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171003_0157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PageStyleOne',
        ),
        migrations.AlterModelOptions(
            name='pagestyleone',
            options={'verbose_name_plural': 'Страница стиль 1'},
        ),
    ]
