# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171003_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStyleTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('name', models.CharField(default='Страница', max_length=250, verbose_name='Название страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, default=datetime.date(2017, 10, 3), null=True, verbose_name='Дата')),
                ('category', models.ManyToManyField(to='main.PageCategory')),
            ],
            options={
                'verbose_name_plural': 'Страница стиль 2',
            },
        ),
    ]
