# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171003_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='page_two',
            field=models.ManyToManyField(to='main.PageStyleTwo', verbose_name='Страница стиль 2'),
        ),
    ]
