# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiler', '0009_delete_spoilerpagebanner'),
        ('banner', '0007_delete_bannerpagewithspoiler'),
        ('main', '0016_pagecategory_page_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('name', models.CharField(default='Страница', max_length=250, verbose_name='Название страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('type_page', models.CharField(choices=[('style-one', 'Стиль 1'), ('style-two', 'Стиль 2'), ('style-three', 'Стиль с баннером'), ('style-four', 'Стиль со спойлером'), ('style-five', 'Стиль с баннером и спойлером')], default='style-one', help_text='Необходимо выбрать стиль того, как будет отражаться страница', max_length=20, verbose_name='Стиль страницы')),
                ('date', models.DateField(blank=True, default=datetime.date(2017, 10, 3), null=True, verbose_name='Дата')),
                ('banner', models.ManyToManyField(help_text='Задайте, если ваш стиль поддерживает баннеры', to='banner.BannerPage', verbose_name='Баннер')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные страницы',
            },
        ),
        migrations.RemoveField(
            model_name='pagecategory',
            name='page_one',
        ),
        migrations.RemoveField(
            model_name='pagecategory',
            name='page_two',
        ),
        migrations.DeleteModel(
            name='PageStyleOne',
        ),
        migrations.DeleteModel(
            name='PageStyleTwo',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ManyToManyField(help_text='Одна или несколько категорий, к которым будет принадлежать страница', to='main.PageCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='page',
            name='spoiler',
            field=models.ManyToManyField(help_text='Задайте, если ваш стиль поддерживает спойлеры', to='spoiler.SpoilerPage', verbose_name='Спойлер'),
        ),
    ]
