# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171003_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecategory',
            name='menu',
            field=models.BooleanField(default=True, help_text='Отметьте, если категория должна отображаться как меню', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2017, 10, 4), null=True, verbose_name='Дата'),
        ),
    ]
