# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171004_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='number',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Порядок'),
        ),
    ]
