# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображения для слайдера (3-5 изображений)', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Слайдер 1',
            },
        ),
        migrations.CreateModel(
            name='Slider2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображения для слайдера (3-5 изображений)', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Слайдер 2',
            },
        ),
        migrations.CreateModel(
            name='Slider3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображения для слайдера (3-5 изображений)', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Слайдер 3',
            },
        ),
        migrations.CreateModel(
            name='Slider4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображения для слайдера (3-5 изображений)', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Слайдер 4',
            },
        ),
        migrations.CreateModel(
            name='Slider5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Выберите изображения для слайдера (3-5 изображений)', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Слайд', max_length=250, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Слайдер 5',
            },
        ),
    ]
