# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider1',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='slider2',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='slider3',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='slider4',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL-адрес'),
        ),
        migrations.AddField(
            model_name='slider5',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL-адрес'),
        ),
    ]
