# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20170925_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider1',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='slider2',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='slider3',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='slider4',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='slider5',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Содержание'),
        ),
    ]
