# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20170926_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider1',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='slider2',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='slider3',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='slider4',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='slider5',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
    ]
