# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('name', models.CharField(default='Страница', max_length=250, verbose_name='Название страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Страница о клиенте',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('name', models.CharField(default='Страница', max_length=250, verbose_name='Название страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Страница о нас',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Выберите логотип клиента', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Фирма', max_length=250, verbose_name='Название фирмы')),
                ('brief', models.CharField(blank=True, help_text='Не более 500 знаков', max_length=500, null=True, verbose_name='Краткое описание')),
                ('phone', models.CharField(blank=True, help_text='Не более 50 знаков', max_length=50, null=True, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, help_text='Не более 100 знаков', max_length=100, null=True, verbose_name='Messenger')),
                ('social_one', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети клиента', max_length=500, null=True, verbose_name='URL-адрес 1')),
                ('social_two', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети клиента', max_length=500, null=True, verbose_name='URL-адрес 2')),
                ('social_three', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети клиента', max_length=500, null=True, verbose_name='URL-адрес 3')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок страницы', max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Введите описание для поисковых систем', max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Введите ключевые слова для поисковых систем', max_length=1000, null=True)),
                ('slug', models.SlugField(help_text='Slug влияет на формирование url адреса и должен быть уникальным', null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Выберите изображения сотрудника', null=True, upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(default='Сотрудник', max_length=250, verbose_name='Имя сотрудника')),
                ('job_title', models.CharField(default='Сотрудник', max_length=250, verbose_name='Должность сотрудника')),
                ('brief', models.CharField(blank=True, help_text='Не более 500 знаков', max_length=500, null=True, verbose_name='Краткое описание')),
                ('phone', models.CharField(blank=True, help_text='Не более 50 знаков', max_length=50, null=True, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, help_text='Не более 100 знаков', max_length=100, null=True, verbose_name='Messenger')),
                ('social_one', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети сотрудника', max_length=500, null=True, verbose_name='URL-адрес 1')),
                ('social_two', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети сотрудника', max_length=500, null=True, verbose_name='URL-адрес 2')),
                ('social_three', models.URLField(blank=True, help_text='Вставьте URL-адрес социальной сети сотрудника', max_length=500, null=True, verbose_name='URL-адрес 3')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
