# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20171004_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcustomer',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='customers',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='aboutcustomer',
            name='customers',
            field=models.ManyToManyField(to='about.Customers', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='aboutcustomer',
            name='team',
            field=models.ManyToManyField(to='about.Team', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='customers',
            field=models.ManyToManyField(to='about.Customers', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='team',
            field=models.ManyToManyField(to='about.Team', verbose_name='Сотрудники'),
        ),
    ]
