# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 8',
            },
        ),
        migrations.CreateModel(
            name='HtmlFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 5',
            },
        ),
        migrations.CreateModel(
            name='HtmlFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 4',
            },
        ),
        migrations.CreateModel(
            name='HtmlNine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 9',
            },
        ),
        migrations.CreateModel(
            name='HtmlOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 1',
            },
        ),
        migrations.CreateModel(
            name='HtmlSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 7',
            },
        ),
        migrations.CreateModel(
            name='HtmlSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 6',
            },
        ),
        migrations.CreateModel(
            name='HtmlTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 10',
            },
        ),
        migrations.CreateModel(
            name='HtmlThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 3',
            },
        ),
        migrations.CreateModel(
            name='HtmlTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HTML', max_length=250, verbose_name='Название')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(help_text='Вставьте отредактированный текст или html')),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'HTML вставка 2',
            },
        ),
    ]
