# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_bannertwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPage',
        ),
        migrations.DeleteModel(
            name='BannerPageWithSpoiler',
        ),
        migrations.DeleteModel(
            name='BannerThree',
        ),
    ]
