# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_bannerpage_bannerpagewithspoiler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerPageWithSpoiler',
        ),
    ]
