# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_delete_bannerpagewithspoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerone',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='bannerthree',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='bannertwo',
            name='number',
            field=models.IntegerField(blank=True, help_text='Установленное число будет влиять на очерёдность отображения блока', null=True, verbose_name='Порядок'),
        ),
    ]
